version: "3.5"
services:
  postgres:
    image: postgres:alpine
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: "fuzzy"
      POSTGRES_USER: "fuzzy"
      POSTGRES_DB: "fuzzy"
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - internal
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  grafana:
    image: grafana/grafana
    hostname: grafana
    environment:
      GF_SECURITY_ADMIN_USER: "fuzzy"
      GF_SECURITY_ADMIN_PASSWORD: "fuzzy"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,briangann-datatable-panel"
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
  registry:
    image: registry:2
    hostname: registry
    environment:
      REGISTRY_AUTH: "htpasswd"
      REGISTRY_AUTH_HTPASSWD_REALM: "Fuzzy Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/registry.pem"
      REGISTRY_HTTP_TLS_KEY: "/certs/registry.pem"
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./registry/auth:/auth
      - ./registry/certs:/certs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
networks:
  internal:
