[package]
name = "fuzzy"
version = "0.1.0"
authors = ["tunnelshade <tunnelshade@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/", features = ["yaml"] }
log = "0.4"
num_cpus = "1.0"
pretty_env_logger = "0.4"
uuid = { version = "0.8", features = ["v4"] }

[build-dependencies]
capnpc = "0.12"
