---
- name: Set cpu frequency governer
  command: cpupower frequency-set -g performance
  become_user: root
  become_method: sudo
  when: ansible_facts['os_family'] == "RedHat"

- name: Copy worker identity
  synchronize:
    src: "certs/{{ inventory_hostname }}.pem"
    dest: "{{ fuzzy_workspace }}/worker.pem"
  tags:
    - "copy-worker-certs"

- name: Copy ca crt
  synchronize:
    src: "certs/ca.crt"
    dest: "{{ fuzzy_workspace }}/ca.crt"
  tags:
    - "copy-worker-certs"
