---
- name: Set cpu frequency governer
  shell:
    cpupower frequency-set -g performance
  become: true
  become_user: root
  when: ansible_facts['os_family'] == "RedHat"
  tags:
    - "tune-worker"

- name: Copy worker identity
  synchronize:
    src: "certs/{{ inventory_hostname }}.pem"
    dest: "{{ fuzzy_workspace }}/worker.pem"
  tags:
    - "copy-worker-certs"

- name: Copy ca crt
  synchronize:
    src: "certs/ca.crt"
    dest: "{{ fuzzy_workspace }}/ca.crt"
  tags:
    - "copy-worker-certs"

- name: Create cert storage location in /etc/docker
  file:
    path: "/etc/docker/certs.d/{{ groups['master'][0] }}:5000"
    state: directory
  become: true
  become_user: root
  tags:
    - "copy-worker-certs"

- name: Trust ca.crt in docker
  copy:
    src: "certs/ca.crt"
    dest: "/etc/docker/certs.d/{{ groups['master'][0] }}:5000/ca.crt"
  become: true
  become_user: root
  tags:
    - "copy-worker-certs"

- name: Docker login to private registry
  docker_login:
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    registry_url: "https://{{ groups['master'][0] }}:5000/"
    ca_cert: "{{ fuzzy_workspace }}/ca.crt"
    validate_certs: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - "docker-login"
