---
- name: Set cpu frequency governer
  shell:
    cpupower frequency-set -g performance
  become: true
  become_user: root
  when: ansible_facts['os_family'] == "RedHat"
  tags:
    - "tune-worker"

- name: Copy worker identity
  synchronize:
    src: "certs/{{ inventory_hostname }}.pem"
    dest: "{{ fuzzy_workspace }}/worker.pem"
  tags:
    - "copy-worker-certs"
