---
- name: Set cpu frequency governer
  shell:
    cpupower frequency-set -g performance
  become: true
  become_user: root
  when: ansible_facts['os_family'] == "RedHat"
  tags:
    - "tune-worker"

- name: Copy worker identity
  synchronize:
    src: "certs/{{ inventory_hostname }}.pem"
    dest: "{{ fuzzy_workspace }}/worker.pem"
  tags:
    - "copy-worker-certs"

- name: Get uid
  getent:
    database: passwd
    key: "{{ ansible_user_id }}"
  tags:
    - "fuzzy-worker-containers"

- name: Get docker group
  getent:
    database: group
    split: ':'
  tags:
    - "test-getent"
    - "fuzzy-worker-containers"

- name: Start container
  vars:
    ansible_python_interpreter: /usr/bin/python3
  docker_container:
    name: fuzzy
    image: "{{ groups['master'][0] }}:5000/{{ fuzzy_image }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ getent_passwd[ansible_user_id][4] }}/{{ fuzzy_workspace_relative }}:/home/fuzzy"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    # No namespace other than filesystem
    detach: yes
    pid_mode: host
    ipc_mode: host
    network_mode: host
    uts: host

    recreate: yes
    pull: yes

    entrypoint: /bin/fuzzy
    working_dir: /home/fuzzy
    user: "{{ getent_passwd[ansible_user_id][1] }}:{{ getent_group['docker'][1] }}"
    command: "worker start --server-url https://{{ groups['master'][0] }}:12700/ -v --name {{ inventory_hostname }} {{ getent_passwd[ansible_user_id][4] }}/{{ fuzzy_workspace_relative }}:/home/fuzzy"
  tags:
    - "fuzzy-worker-containers"
