---
- name: Install libpq
  package:
    name: libpqxx-devel
    state: present
  become_user: root
  become_method: sudo
  when: ansible_facts['os_family'] == "RedHat"

- name: Install diesel cli
  command: cargo install diesel_cli --no-default-features --features "postgres"
  args:
    creates: ~/.cargo/bin/diesel

- name: Copy ca crt
  synchronize:
    src: "certs/ca.crt"
    dest: "{{ fuzzy_workspace }}/ca.crt"
  tags:
    - "sync-master-setup"

- name: Copy master identity
  synchronize:
    src: "certs/{{ inventory_hostname }}.pem"
    dest: "{{ fuzzy_workspace }}/server.pem"
  tags:
    - "copy-worker-certs"

# Infra related
- name: Copy docker-compose.yml
  synchronize:
    src: docker-compose.yml
    dest: "{{ fuzzy_workspace }}/docker-compose.yml"
  tags:
    - "sync-master-setup"

- name: Copy grafana volume
  synchronize:
    src: grafana
    dest: "{{ fuzzy_workspace }}"
  tags:
    - "sync-master-setup"

# Registry related tasks
- name: Create registry certs
  file:
    path: "{{ fuzzy_workspace }}/registry/certs"
    state: directory
    recurse: yes
  tags:
    - "sync-master-setup"

- name: Create registry auth dir
  file:
    path: "{{ fuzzy_workspace }}/registry/auth"
    state: directory
    recurse: yes
  tags:
    - "sync-master-setup"
- name: Copy registry certs
  synchronize:
    src: "certs/{{ inventory_hostname }}.pem"
    dest: "{{ fuzzy_workspace }}/registry/certs/registry.pem"
  tags:
    - "sync-master-setup"

- name: Generate auth for registry
  shell: htpasswd -Bbn {{ registry_username }} {{ registry_password }} > {{ fuzzy_workspace }}/registry/auth/htpasswd
  tags:
    - "sync-master-setup"

- name: Ensure services are running
  docker_compose:
    project_src: "{{ fuzzy_workspace }}"
  register: output
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - "master-services-up"

- name: Run db migrations
  shell:
    cmd: ~/.cargo/bin/diesel migration run --database-url postgres://fuzzy:fuzzy@localhost:5432/fuzzy
    chdir: "{{ fuzzy_src }}"
