---
- name: Copy master identity
  synchronize:
    src: "certs/{{ inventory_hostname }}.pem"
    dest: "{{ fuzzy_workspace }}/server.pem"
  tags:
    - "copy-worker-certs"

# Infra related
- name: Copy docker-compose.yml
  synchronize:
    src: docker-compose.yml
    dest: "{{ fuzzy_workspace }}/docker-compose.yml"
  tags:
    - "sync-master-setup"
    - "update-grafana"

- name: Copy grafana volume
  synchronize:
    src: grafana
    dest: "{{ fuzzy_workspace }}"
  tags:
    - "sync-master-setup"
    - "update-grafana"

# Registry related tasks
- name: Create registry certs
  file:
    path: "{{ fuzzy_workspace }}/registry/certs"
    state: directory
    recurse: yes
  tags:
    - "sync-master-setup"

- name: Create registry auth dir
  file:
    path: "{{ fuzzy_workspace }}/registry/auth"
    state: directory
    recurse: yes
  tags:
    - "sync-master-setup"
- name: Copy registry certs
  synchronize:
    src: "certs/{{ inventory_hostname }}.pem"
    dest: "{{ fuzzy_workspace }}/registry/certs/registry.pem"
  tags:
    - "sync-master-setup"

- name: Generate auth for registry
  shell: htpasswd -Bbn {{ registry_username }} {{ registry_password }} > {{ fuzzy_workspace }}/registry/auth/htpasswd
  tags:
    - "sync-master-setup"

- name: Ensure services are running
  docker_compose:
    project_src: "{{ fuzzy_workspace }}"
    state: present
    restarted: yes
  register: output
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - "master-services-up"
    - "update-grafana"

- name: Get uid
  getent:
    database: passwd
    key: "{{ ansible_user_id }}"
  tags:
    - "fuzzy-master-container"

- name: Get docker group
  getent:
    database: group
    split: ':'
  tags:
    - "fuzzy-master-container"

- name: Start fuzzy master
  vars:
    ansible_python_interpreter: /usr/bin/python3
  docker_container:
    name: fuzzy
    image: "{{ groups['master'][0] }}:5000/{{ fuzzy_image }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ getent_passwd[ansible_user_id][4] }}/{{ fuzzy_workspace_relative }}:/home/fuzzy"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    # No namespace other than filesystem
    detach: yes
    pid_mode: host
    ipc_mode: host
    network_mode: host
    uts: host

    recreate: yes
    pull: yes

    entrypoint: /bin/fuzzy
    working_dir: /home/fuzzy
    user: "{{ getent_passwd[ansible_user_id][1] }}:{{ getent_group['docker'][1] }}"
    command: "master start --db {{ db_conn_string }} -v --listen-addr 0.0.0.0:12700"
  tags:
    - "fuzzy-master-container"
