---
# This playbook helps in deploying fuzzy master & worker
- name: Apply master configurations
  hosts: master
  roles:
    - common
    - master

- name: Apply worker configurations
  hosts: workers
  roles:
    - common
    - worker
