{
 "title": "Fuzzy",
 "description": "A simple dashboard for fuzzy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "task", "query": "select name from tasks;" }
  ]
 },
 "panels": [
  { "title": "$task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "task" },
  {
   "title": "Crashes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM crashes\nWHERE\n  worker_task_id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = '$task' AND worker_tasks.task_id = tasks.id) AND\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "workers",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  uuid,\n  name,\n  workers.cpus as \"Total CPUs\",\n  worker_tasks.cpus as \"Allocated for task\",\n  memory\nFROM workers, worker_tasks\nWHERE\n  workers.id = worker_tasks.worker_id AND\n  worker_tasks.id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = '$task')\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Corpus Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM corpora\nWHERE\n  worker_task_id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = '$task' AND worker_tasks.task_id = tasks.id) AND\n  $__timeFilter(created_at)"
    }
   ]
  },
  {
   "title": "coverage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  coverage\nFROM fuzz_stats\nWHERE\n  worker_task_id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = '$task' AND worker_tasks.task_id = tasks.id) AND\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "execs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  execs\nFROM fuzz_stats\nWHERE\n  worker_task_id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = '$task' AND worker_tasks.task_id = tasks.id) AND\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  }
 ]
}