pub const WORKER_CONNECT_ADDR_ENV_KEY: &str = "FUZZY_WORKER_CONNECT_ADDR";
pub const WORKER_CONNECT_CACERT_ENV_KEY: &str = "FUZZY_WORKER_CONNECT_CA_CERT_PATH";
pub const WORKER_CONNECT_WORKERPEM_ENV_KEY: &str = "FUZZY_WORKER_CONNECT_WORKER_PEM_PATH";
