pub const WORKER_CONNECT_ADDR_ENV_KEY: &str = "FUZZY_WORKER_CONNECT_ADDR";
pub const WORKER_CONNECT_CACERT_ENV_KEY: &str = "FUZZY_WORKER_CONNECT_CA_CERT_PATH";
pub const WORKER_CONNECT_WORKERPEM_ENV_KEY: &str = "FUZZY_WORKER_CONNECT_WORKER_PEM_PATH";

pub const WORKER_CONTAINER_VOLUME_MAP: &str = "FUZZY_CONTAINER_VOLUME_MAP";

pub const FUZZY_CONNECT_URL: &str = "FUZZY_CONNECT_URL";
pub const FUZZY_CA_CERT: &str = "FUZZY_CA_CERT";
pub const FUZZY_CLIENT_PEM: &str = "FUZZY_CLIENT_PEM";
