{
 "title": "Fuzzy",
 "description": "A simple dashboard for fuzzy",
 "time": { "from": "now-10d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "task", "query": "select name from tasks;" },
   { "name": "worker", "query": "select name from workers;" }
  ]
 },
 "panels": [
  {
   "title": "Task - $task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "task",
   "collapsed": true,
   "panels": [
    {
     "title": "Corpus Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM corpora\nWHERE\n  worker_task_id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = $task AND worker_tasks.task_id = tasks.id) AND\n  $__timeFilter(created_at)"
      }
     ]
    },
    {
     "title": "Total Crashes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM crashes\nWHERE\n  worker_task_id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = $task AND worker_tasks.task_id = tasks.id) AND\n  $__timeFilter(created_at)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Unique Verified Crashes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM crashes\nWHERE\n  worker_task_id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = $task AND worker_tasks.task_id = tasks.id) AND\n  crashes.duplicate isnull AND\n  crashes.verified = true AND\n  $__timeFilter(created_at)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Profile",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 13, "x": 11, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT\n  profile\nFROM tasks\nWHERE\n  name = $task\nORDER BY 1"
      }
     ]
    },
    {
     "title": "workers",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT\n  workers.name,\n  workers.cpus as \"Total CPUs\",\n  worker_tasks.cpus as \"Allocated for task\",\n  memory,\n  worker_tasks.running,\n  worker_tasks.active\nFROM worker_tasks INNER JOIN tasks ON worker_tasks.task_id = tasks.id AND tasks.name = $task\nINNER JOIN workers ON worker_tasks.worker_id = workers.id\nORDER BY 1"
      }
     ]
    },
    {
     "title": "coverage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  branch_coverage,\n  line_coverage,\n  function_coverage\nFROM fuzz_stats\nWHERE\n  worker_task_id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = $task AND worker_tasks.task_id = tasks.id) AND\n  $__timeFilter(created_at)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "execs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  execs\nFROM fuzz_stats\nWHERE\n  worker_task_id = ANY(SELECT worker_tasks.id FROM worker_tasks, tasks WHERE tasks.name = $task AND worker_tasks.task_id = tasks.id) AND\n  $__timeFilter(created_at)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Crashes",
     "type": "table-old",
     "gridPos": { "h": 25, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "SELECT\n  crashes.created_at AS \"Time\",\n  output,\n  verified,\n  CONCAT('Id: ', crashes.id, chr(13), 'Duplicate Of: ', duplicate, chr(13), 'Checksum: ', checksum) AS \"Metadata\"\nFROM crashes INNER JOIN  worker_tasks ON crashes.worker_task_id = worker_tasks.id\nINNER JOIN tasks ON worker_tasks.task_id = tasks.id AND tasks.name = $task\nWHERE\n  $__timeFilter(crashes.created_at)\nORDER BY crashes.created_at asc;"
      }
     ]
    }
   ]
  },
  {
   "title": "Worker - $worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "worker",
   "collapsed": true,
   "panels": [
    {
     "title": "$worker - Logs",
     "type": "table",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  level,\n  target,\n  message\nFROM trace_events\nWHERE\n  worker_id = (SELECT id FROM workers WHERE name = $worker) AND\n  $__timeFilter(created_at)\nORDER BY id desc"
      }
     ]
    },
    {
     "title": "$worker - Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 19, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  memory_total,\n  memory_used,\n  swap_total,\n  swap_used\nFROM sys_stats\nWHERE\n  worker_id = (SELECT id FROM workers WHERE name = $worker) AND\n  $__timeFilter(created_at)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "$worker - Aggregate CPU",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "rawSql": "SELECT\n  created_at AS \"time\",\n  cpu_user_time,\n  cpu_system_time,\n  cpu_idle_time\nFROM sys_stats\nWHERE\n  worker_id = (SELECT id FROM workers WHERE name = $worker) AND\n  $__timeFilter(created_at)\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}